# Generated by Django 5.0.6 on 2024-06-05 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('screencast', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='Без имени', help_text='Напишите имя', max_length=65, verbose_name='Имя')),
                ('question_text', models.CharField(help_text='Задайте вопрос', max_length=200, verbose_name='Вопрос')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False, verbose_name='Отвечен')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='screencast.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
