# Generated by Django 5.0.6 on 2024-06-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Имя"),
        ),
    ]
