# Generated by Django 5.0.6 on 2024-06-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0003_user_lastname_user_middlename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='business_area',
            field=models.CharField(default='Безработный', max_length=255, verbose_name='Сфера деятельности'),
        ),
    ]
