# Generated by Django 5.0.6 on 2024-06-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0004_alter_user_business_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_corporate',
        ),
        migrations.AddField(
            model_name='user',
            name='entity',
            field=models.CharField(choices=[('LP', 'Юридическое лицо'), ('NP', 'Физическое лицо')], default='NP', max_length=17, verbose_name='Физ./Юр. лицо'),
        ),
    ]
