# Generated by Django 5.0.6 on 2024-06-05 13:43

import django.db.models.deletion
import quiz.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('screencast', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название викторины')),
                ('description', models.TextField(blank=True, verbose_name='Описание викторины')),
                ('banner', models.ImageField(blank=True, upload_to=quiz.models.user_directory_path, verbose_name='Баннер викторины')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screencast.event', verbose_name='Мероприятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Викторина',
                'verbose_name_plural': 'Викторины',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Вопрос')),
                ('image', models.ImageField(blank=True, upload_to=quiz.models.user_directory_path, verbose_name='Изображение')),
                ('correct_answer', models.CharField(max_length=128, verbose_name='Правильный ответ')),
                ('wrong_answer_1', models.CharField(max_length=128, verbose_name='Ошибочный ответ')),
                ('wrong_answer_2', models.CharField(blank=True, max_length=128, verbose_name='Ошибочный ответ')),
                ('wrong_answer_3', models.CharField(blank=True, max_length=128, verbose_name='Ошибочный ответ')),
                ('wrong_answer_4', models.CharField(blank=True, max_length=128, verbose_name='Ошибочный ответ')),
                ('wrong_answer_5', models.CharField(blank=True, max_length=128, verbose_name='Ошибочный ответ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='Викторина')),
            ],
            options={
                'verbose_name': 'Вопрос викторины',
                'verbose_name_plural': 'Вопросы викторины',
            },
        ),
    ]
