# Generated by Django 5.0.6 on 2024-06-18 14:23

import django.core.validators
import django.db.models.deletion
import screencast.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название мероприятия')),
                ('start_date', models.DateTimeField(blank=True, verbose_name='Дата/время проведения')),
                ('pdf', models.FileField(blank=True, upload_to=screencast.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Презентация в PDF')),
                ('current_slide', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название/номер слайда')),
                ('jpeg', models.FileField(blank=True, upload_to=screencast.models.user_directory_path, verbose_name='Слайд в JPEG')),
                ('scheduled_time', models.TimeField(blank=True, verbose_name='Запланированное время на блок')),
                ('time_spent', models.TimeField(blank=True, verbose_name='Потраченное время на блок')),
                ('order', models.IntegerField(unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screencast.event', verbose_name='Мероприятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
    ]
