# Generated by Django 5.0.6 on 2024-06-17 15:47

import django.core.validators
import screencast.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screencast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pdf',
            field=models.FileField(blank=True, upload_to=screencast.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Презентация в PDF'),
        ),
    ]
