# Generated by Django 5.0.6 on 2024-06-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screencast', '0002_alter_slide_scheduled_time_alter_slide_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='data',
            field=models.TextField(blank=True, verbose_name='Информация'),
        ),
    ]
