# Generated by Django 5.0.6 on 2024-06-18 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screencast', '0003_slide_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='slide',
            constraint=models.UniqueConstraint(fields=('event', 'order'), name='unique_order_per_event'),
        ),
    ]
