# Generated by Django 5.0.6 on 2024-06-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screencast', '0004_slide_unique_order_per_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='order',
            field=models.IntegerField(),
        ),
    ]
