# Generated by Django 5.0.6 on 2024-06-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screencast', '0005_alter_slide_order'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='slide',
            name='unique_order_per_event',
        ),
        migrations.AlterUniqueTogether(
            name='slide',
            unique_together={('event', 'order')},
        ),
    ]
