# Generated by Django 5.0.6 on 2024-06-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screencast', '0007_alter_slide_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pdf_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='slide',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
