# Generated by Django 5.0.6 on 2024-06-19 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screencast', '0008_event_pdf_uploaded_alter_slide_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ('order',), 'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды'},
        ),
    ]
