# Generated by Django 5.0.6 on 2024-06-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screencast', '0009_alter_slide_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды'},
        ),
    ]
